/*

Die Dimensionsion sind gegeben durch GW2
um den Nullpunkt zu verschieben muss IMMER durch die SCENE_HEIGHT 600 abstrahiert werden.
*/
//
#ifndef DIMENSIONS_H
#define DIMENSIONS_H

#define SCENE_WIDTH 1920
#define SCENE_HEIGHT 1080

#define SCALE_FACTOR 1
#define SCALE_FACTOR_REAL 4.0

#define TEST_OFFSET_X 3
// Dimensions of the stations
#define STATION_WIDTH ((220/SCALE_FACTOR_REAL)*SCALE_FACTOR)
#define STATION_HEIGHT ((280/SCALE_FACTOR_REAL)*SCALE_FACTOR)

#define CHARGE_STATION_WIDTH ((40/SCALE_FACTOR_REAL)*SCALE_FACTOR)
#define CHARGE_STATION_HEIGHT ((70/SCALE_FACTOR_REAL)*SCALE_FACTOR)

// Positions of the manufacturing stations
#define STATION1_X ((1140/SCALE_FACTOR_REAL)*SCALE_FACTOR)
#define STATION1_Y ((2800/SCALE_FACTOR_REAL)*SCALE_FACTOR)                                       // Y von unten
#define STATION1_BOTTOM_LEFT_Y (STATION1_Y - STATION_HEIGHT) // untere linke Ecke Y
#define STATION1_BOTTOM_RIGHT_X (STATION1_X + STATION_WIDTH) // untere rechte Ecke X
#define STATION1_BOTTOM_LEFT_X STATION1_X                    // untere linke Ecke X
#define STATION1_TOP_LEFT_Y STATION1_Y                       // obere linke Ecke Y
#define STATION1_TOP_RIGHT_X (STATION1_X + STATION_WIDTH)    // obere rechte Ecke X

#define STATION2_X ((2360/SCALE_FACTOR_REAL)*SCALE_FACTOR)
#define STATION2_Y ((2800/SCALE_FACTOR_REAL)*SCALE_FACTOR)
#define STATION2_BOTTOM_LEFT_Y (STATION2_Y - STATION_HEIGHT)
#define STATION2_BOTTOM_RIGHT_X (STATION2_X + STATION_WIDTH)
#define STATION2_BOTTOM_LEFT_X STATION2_X
#define STATION2_TOP_LEFT_Y STATION2_Y
#define STATION2_TOP_RIGHT_X (STATION2_X + STATION_WIDTH)

#define STATION3_X ((3570/SCALE_FACTOR_REAL)*SCALE_FACTOR)
#define STATION3_Y ((2800/SCALE_FACTOR_REAL)*SCALE_FACTOR)
#define STATION3_BOTTOM_LEFT_Y (STATION3_Y - STATION_HEIGHT)
#define STATION3_BOTTOM_RIGHT_X (STATION3_X + STATION_WIDTH)
#define STATION3_BOTTOM_LEFT_X STATION3_X
#define STATION3_TOP_LEFT_Y STATION3_Y
#define STATION3_TOP_RIGHT_X (STATION3_X + STATION_WIDTH)

#define STATION4_X ((4790/SCALE_FACTOR_REAL)*SCALE_FACTOR)
#define STATION4_Y ((2800/SCALE_FACTOR_REAL)*SCALE_FACTOR)
#define STATION4_BOTTOM_LEFT_Y (STATION4_Y - STATION_HEIGHT)
#define STATION4_BOTTOM_RIGHT_X (STATION4_X + STATION_WIDTH)
#define STATION4_BOTTOM_LEFT_X STATION4_X
#define STATION4_TOP_LEFT_Y STATION4_Y
#define STATION4_TOP_RIGHT_X (STATION4_X + STATION_WIDTH)

// Positions of the charging stations
#define CHARGE_STATION1_X ((6270/SCALE_FACTOR_REAL)*SCALE_FACTOR)
#define CHARGE_STATION1_Y (((3420+100)/SCALE_FACTOR_REAL)*SCALE_FACTOR) // Y von unten
#define CHARGE_STATION1_BOTTOM_LEFT_Y \
(CHARGE_STATION1_Y - CHARGE_STATION_HEIGHT) // untere linke Ecke Y
#define CHARGE_STATION1_BOTTOM_RIGHT_X \
    (CHARGE_STATION1_X + CHARGE_STATION_WIDTH)          // untere rechte Ecke X
#define CHARGE_STATION1_BOTTOM_LEFT_X CHARGE_STATION1_X // untere linke Ecke X
#define CHARGE_STATION1_TOP_LEFT_Y CHARGE_STATION1_Y    // obere linke Ecke Y
#define CHARGE_STATION1_TOP_RIGHT_X \
    (CHARGE_STATION1_X + CHARGE_STATION_WIDTH) // obere rechte Ecke X

#define CHARGE_STATION2_X ((6850/SCALE_FACTOR_REAL)*SCALE_FACTOR)
#define CHARGE_STATION2_Y (((3420+100)/SCALE_FACTOR_REAL)*SCALE_FACTOR) // Y von unten
#define CHARGE_STATION2_BOTTOM_LEFT_Y \
    (CHARGE_STATION2_Y - CHARGE_STATION_HEIGHT) // untere linke Ecke Y
#define CHARGE_STATION2_BOTTOM_RIGHT_X \
    (CHARGE_STATION2_X + CHARGE_STATION_WIDTH)          // untere rechte Ecke X
#define CHARGE_STATION2_BOTTOM_LEFT_X CHARGE_STATION2_X // untere linke Ecke X
#define CHARGE_STATION2_TOP_LEFT_Y CHARGE_STATION2_Y    // obere linke Ecke Y
#define CHARGE_STATION2_TOP_RIGHT_X \
    (CHARGE_STATION2_X + CHARGE_STATION_WIDTH) // obere rechte Ecke X

#endif // DIMENSIONS_H
